before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: AgNiwmci/wbl6kZ097SxSn1wHuy7nl9ASp942/1+/Rz4rs8g8Hde8UUz0+c5zy5bGoXpMzHO1QjNfNjm04nVT60Is2vLfGzr7baAZwWCGHWUTgUKJHL7CWT71Vxlqtnteh2z4FSKbEuSncYOp6pcL5Qb5dhcoAaeaPBtJYdXJJTBNGb7Qbsh3+OwwLxIn5wKCuUEZXmyovKhUbA6XuD2h4leTdBk9O4GvwtxWYeQTI0ErN9QX/P7Q/mlrO9Qnpycqx/+U4XvRbW/r9kKQCwlnMnT5+ST7YIsxhJYfKjuhTZG/6GlzxWIhwihkNjwSbSfVmYfu8pmtyVqg5qODQppRXe47iPI/eqodvjTnZI3TxI6fwmXzQBfWk4sBLQxXeeMvZCBAJEpvvT99Wfnbijh4pQqphAUKI6cuRArG8aIKwwk1Cg3GL2Yk6lKpzbjdQZaifROhgCmbiZMtFeRyajG1Efs0IZuPEsS4OTRABWJnCrsCd1rHP2W1WhA37cu65ZEvdfQXe78j2NqxqvBthiOzOBd1VC8jYhyrw4TwuoGnfLspoKpKJsPfRvS80UDsyThKRSPK6aK3I7ta7ggYFu25GEqzr09ZkwTVp3vGwllwR1LaGxpNrVOJlknAHOgqJ7iTJzbefHFSd+RMi1VLyfeyNdPyomy+0CLsTWyRqJbrXA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
